reactiverse/es4x

- src/main/java/io/reactiverse/es4x/jul/ES4XFormatter.java
- src/main/java/io/reactiverse/es4x/nashorn/runtime/Console.java
- src/main/resources/vertx-default-jul-logging.properties
- src/test/java/io/reactiverse/es4x/nashorn/LoggerTest.java
- src/test/resources/exp.js
> Format exceptions to the console

- docs/README.md
The default snippet of code doesn't work app is not compatible with request handler.
> fix the example

- codegen/src/main/java/io/reactiverse/es4x/codegen/generator/IndexDTS.java
TemplateEngine in module `@vertx/web` is extends from TemplateEngine in module `@vertx/web-common`
> fix same name with super type

- codegen/pom.xml
- codegen/src/test/java/io/reactiverse/es4x/codegen/generator/UtilTest.java
Hi,
Thank you for your submission through our website
These tests have been created by [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully, these tests should help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other particular classes that you consider important.
> Add unit tests for io.reactiverse.es4x.codegen.generator.Util

- CHANGELOG.md
- es4x/src/main/java/io/reactiverse/es4x/ES4X.java
- es4x/src/main/java/io/reactiverse/es4x/impl/command/ES4XRunCommand.java
- es4x/src/main/java/io/reactiverse/es4x/impl/command/ES4XStartCommand.java
- es4x/src/main/java/io/reactiverse/es4x/impl/graal/GraalEngine.java
- es4x/src/test/java/io/reactiverse/es4x/test/PolyglotTest.java
- pm/publish.sh
- pom.xml
Add a flag to the run command to enable/disable graal `Polyglot` access from scripts
> Fixes #146

- es4x/src/main/java/io/reactiverse/es4x/impl/command/ES4XRunCommand.java
- es4x/src/main/java/io/reactiverse/es4x/impl/graal/VertxFileSystem.java
- es4x/src/test/java/io/reactiverse/es4x/test/ESMPrefixTest.java
- es4x/src/test/resources/prefix/verticle4.mjs
- pm/src/main/java/io/reactiverse/es4x/commands/InstallCommand.java
> Fixes #139

- docs/get-started/contributing.md
- docs/zh/get-started/contributing.md
Remove redundant  double quotes
> Remove redundant  double quotes

- docs/get-started/package.md
according to https://docs.docker.com/engine/reference/commandline/build/
> Doc:docker build arg option error

- docs/zh/advanced/README.md
- docs/zh/get-started/package.md
mirror change of 
https://github.com/reactiverse/es4x/pull/176/files
> Corresponding doc update of original doc changes

- es4x/src/main/java/io/reactiverse/es4x/ECMAEngine.java
- es4x/src/main/java/io/reactiverse/es4x/ESVerticleFactory.java
- es4x/src/main/java/io/reactiverse/es4x/JSVerticleFactory.java
- es4x/src/main/java/io/reactiverse/es4x/MJSVerticleFactory.java
- es4x/src/main/java/io/reactiverse/es4x/Runtime.java
We want to customize how js verticles are created and to inject functions and objects (in context's bindings)
> Open VerticleFactory and Runtime for extension. 

- docs/advanced/README.md
Hi, I was reading the docs and found this small typo so I fixed it for you 😉
> Small typo

- pm/src/assembly/bin/es4x
- pm/src/assembly/bin/es4x-cli.js
- pm/src/assembly/bin/es4x.cmd
- pm/src/main/java/io/reactiverse/es4x/commands/Install.java
> Allow user override of default logging properties

- .github/workflows/gh-pages.yml
- package.json
> Adding an automated deployment of the website

- docs/.vuepress/config.js
This closes [this](https://github.com/reactiverse/es4x/pull/411#issuecomment-703230107) issue
> Translated config labels

- docs/.vuepress/config.js
Labels translated according to https://github.com/reactiverse/es4x/pull/413#issuecomment-703228009
> Labels translated to Russian

- docs/gr/examples/README.md
- docs/gr/examples/hello-world/index.js
- docs/gr/examples/hello-world/package.json
- docs/gr/examples/postgresql/index.js
- docs/gr/examples/postgresql/package.json
- docs/gr/examples/web-application/index.js
- docs/gr/examples/web-application/package.json
This PR closes [this](https://github.com/reactiverse/es4x/issues/421) issue.
> Added and translated the examples directory

- docs/.vuepress/config.js
Patch to [comment](https://github.com/reactiverse/es4x/pull/416#issuecomment-703228775) in [PR #416 ](https://github.com/reactiverse/es4x/pull/416#issue-497002438)
> Update labels for polish translation in config.js

- codegen/src/main/java/io/reactiverse/es4x/codegen/generator/IndexDTS.java
- codegen/src/main/java/io/reactiverse/es4x/codegen/generator/Util.java
- es4x/src/main/java/io/reactiverse/es4x/ECMAEngine.java
- es4x/src/test/java/io/reactiverse/es4x/test/FutureTest.java
- es4x/src/test/resources/future/response.js
- pom.xml
Follow up on: https://github.com/vert-x3/vertx-codegen/issues/317
> Adapt codegen to transform Future to PromiseLike

- es4x/pom.xml
- pm/src/main/java/io/reactiverse/es4x/cli/VertxPatch.java
> Make Patch a semi-public feature as it is needed for non maven project

- .travis.yml
> Bump to 16

- es4x/src/main/java/io/reactiverse/es4x/ES4X.java
- pm/src/assembly/bin/es4x
- pm/src/assembly/bin/es4x-completion.bash
- pm/src/assembly/pm.xml
- pm/src/main/java/io/reactiverse/es4x/cli/PM.java
This PR adds support for bash completion of vert.x commands.
> Adding bash completion to the CLI

- es4x/src/test/java/io/reactiverse/es4x/test/CommonJSExportsTest.java
- es4x/src/test/resources/lib/exports/exports.js
- es4x/src/test/resources/lib/exports/index.js
> Try to reproduce the RXJS bug

- docs/advanced/vertx.md
As discussed in #585, adding the async block around the example code to make it work.
> Updating async instructions
